import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { copy, isLocale, Locale } from "@/lib/i18n";
import { db } from "@/lib/db";
import type { Job, NewsPost } from "@prisma/client";
import { BriefcaseBusiness, Shield, HeartPulse, Wrench, ArrowUpLeft, ArrowUpRight, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
const iconMap: Record<string, React.ReactNode> = { police:<Shield size={19}/>, ems:<HeartPulse size={19}/>, mechanic:<Wrench size={19}/>, government:<BriefcaseBusiness size={19}/> };
export default async function Home({params}:{params:Promise<{locale:string}>}){
 const {locale:raw}=await params;if(!isLocale(raw))notFound();const locale=raw as Locale;const t=copy[locale];
 let jobs: Job[] = [], news: NewsPost[] = [];
 try { [jobs, news] = await Promise.all([db.job.findMany({where:{active:true},orderBy:{sortOrder:"asc"},take:4}),db.newsPost.findMany({where:{published:true},orderBy:{createdAt:"desc"},take:2})]); } catch { /* Content is optional during first deployment. */ }
 return <><SiteHeader locale={locale}/><main>
  <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">{t.heroEyebrow}</span><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="hero-actions"><a className="btn btn-primary" href="https://discord.com" target="_blank">{t.discord} {locale==='ar'?<ArrowUpLeft size={18}/>:<ArrowUpRight size={18}/>}</a><Link className="btn btn-ghost" href={`/${locale}/rules`}>{t.rules}</Link></div><div style={{marginTop:28,color:"#8f8b84",fontSize:13}}><span className="status-dot"/>{t.status}: <b style={{color:"#eee"}}>{t.online}</b></div></div>
  <div className="hero-art"><div className="logo-orbit"><Image src="/prime-rp-logo.png" alt="Prime RP" width={600} height={400} priority/></div></div></div></section>
  <section id="about" className="section"><div className="container"><div className="section-head"><div><span className="section-kicker">Prime RP</span><h2>{t.explore}</h2></div><p>{t.heroText}</p></div><div className="cards"><div className="card"><div className="icon"><Sparkles size={19}/></div><h3>{locale==='ar'?'الانغماس':'Immersion'}</h3><p>{locale==='ar'?'تفاصيل صغيرة تصنع تجربة أكبر.':'Small details create a bigger experience.'}</p></div><div className="card"><div className="icon"><Shield size={19}/></div><h3>{locale==='ar'?'المجتمع':'Community'}</h3><p>{locale==='ar'?'بيئة واضحة تحترم اللاعب والقصة.':'A clear environment built around players and stories.'}</p></div><div className="card"><div className="icon"><BriefcaseBusiness size={19}/></div><h3>{locale==='ar'?'المسارات':'Careers'}</h3><p>{locale==='ar'?'طرق متعددة لبناء شخصية لها معنى.':'Multiple paths to build a meaningful character.'}</p></div><div className="card"><div className="icon"><HeartPulse size={19}/></div><h3>{locale==='ar'?'الدعم':'Support'}</h3><p>{locale==='ar'?'دعم منظم وتجربة أسهل للمجتمع.':'Organized support for a smoother community experience.'}</p></div></div></div></section>
  <section className="section" style={{paddingTop:20}}><div className="container"><div className="section-head"><div><span className="section-kicker">Careers</span><h2>{t.jobsTitle}</h2></div><p>{t.jobsText}</p></div><div className="cards">{jobs.map(j=><Link className="card" href={`/${locale}/jobs`} key={j.id}><div className="icon">{iconMap[j.icon]||<BriefcaseBusiness size={19}/>}</div><h3>{locale==='ar'?j.titleAr:j.titleEn}</h3><p>{locale==='ar'?j.descriptionAr:j.descriptionEn}</p></Link>)}</div></div></section>
  <section className="section" style={{paddingTop:20}}><div className="container"><div className="section-head"><div><span className="section-kicker">Updates</span><h2>{t.latest}</h2></div><Link className="btn" href={`/${locale}/news`}>{t.viewAll}</Link></div><div className="news-grid">{news.map((n,i)=><article className={`news-card ${i===0?'featured':''}`} key={n.id}><span className="tag">PRIME NEWS</span><h3>{locale==='ar'?n.titleAr:n.titleEn}</h3><p>{locale==='ar'?n.excerptAr:n.excerptEn}</p></article>)}</div></div></section>
  <section className="section" style={{paddingTop:20}}><div className="container"><div className="rules-panel"><div className="rule-hero"><span className="section-kicker">Rules</span><h2>{t.rulesTitle}</h2><p style={{color:"#aaa",lineHeight:1.8}}>{t.rulesText}</p><Link className="btn btn-primary" href={`/${locale}/rules`}>{t.rules}</Link></div><div className="rule-list"><div className="rule-row"><b>01</b><div style={{marginTop:8}}>{locale==='ar'?'احترم تجربة الرول بلاي واللاعبين خلف الشخصيات.':'Respect the roleplay and the people behind it.'}</div></div><div className="rule-row"><b>02</b><div style={{marginTop:8}}>{locale==='ar'?'حافظ على تفاعل عادل، واضح، ومناسب لسياق اللعب.':'Keep interactions fair, immersive and clear.'}</div></div><div className="rule-row"><b>03</b><div style={{marginTop:8}}>{locale==='ar'?'اتبع تعليمات الإدارة وحل النزاعات عبر الدعم.':'Follow staff instructions and resolve disputes through support.'}</div></div></div></div></div></section>
 </main><SiteFooter locale={locale}/></>;
}
